export const notifications = [
  {
    avatar:
      "https://robohash.org/officiisdoloremquevitae.png?size=50x50&set=set1",
    id: 1,
    first_name: "Temp",
    last_name: "Tixall",
    email: "ttixall0@arstechnica.com",
    gender: "Male",
    content:
      "justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est",
    created: "1676567377420",
  },
  {
    avatar: "https://robohash.org/etlaborumenim.png?size=50x50&set=set1",
    id: 2,
    first_name: "Maggee",
    last_name: "Championnet",
    email: "mchampionnet1@amazon.co.jp",
    gender: "Female",
    content:
      "eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncuseleifend donec ut dolor morbi vel lectus in quam fringilla rhoncuseleifend donec ut dolor morbi vel lectus in quam fringilla rhoncusfringilla rhoncuseleifend donec ut dolor morbi vel lectus in qlla rhoncusfringilla rhoncuseleifend donec ut dolor morbi vel lectus in qlla rhoncusfringilla rhoncuseleifend donec ut dolor morbi vel lectus in qlla rhoncusfringilla rhoncuseleifend donec ut dolor morbi vel lectus in qlla rhoncusfringilla rhoncuseleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus",
    created: "1676567377420",
  },
  {
    avatar: "https://robohash.org/quodaliasaut.png?size=50x50&set=set1",
    id: 3,
    first_name: "Carla",
    last_name: "Brandham",
    email: "cbrandham2@4shared.com",
    gender: "Female",
    content:
      "eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus",
    created: "1660498730000",
  },
  {
    avatar:
      "https://robohash.org/laborevoluptassapiente.png?size=50x50&set=set1",
    id: 4,
    first_name: "Georgie",
    last_name: "Gentzsch",
    email: "ggentzsch3@issuu.com",
    gender: "Male",
    content:
      "id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi",
    created: "1670326664000",
  },
  {
    avatar: "https://robohash.org/estquaeperferendis.png?size=50x50&set=set1",
    id: 5,
    first_name: "Estella",
    last_name: "Harbard",
    email: "eharbard4@businessweek.com",
    gender: "Female",
    content:
      "lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue",
    created: "1674707122000",
  },
  {
    avatar: "https://robohash.org/etnullaenim.png?size=50x50&set=set1",
    id: 6,
    first_name: "Hewe",
    last_name: "Harrismith",
    email: "hharrismith5@rediff.com",
    gender: "Male",
    content:
      "lobortis est phasellus sit amet erat nulla tempus vivamus in felis",
    created: "1665457762000",
  },
  {
    avatar: "https://robohash.org/eaautdolores.png?size=50x50&set=set1",
    id: 7,
    first_name: "Nicolai",
    last_name: "Whife",
    email: "nwhife6@msn.com",
    gender: "Male",
    content:
      "consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce",
    created: "1645998150000",
  },
  {
    avatar: "https://robohash.org/athiciusto.png?size=50x50&set=set1",
    id: 8,
    first_name: "Jobey",
    last_name: "Hibling",
    email: "jhibling7@clickbank.net",
    gender: "Female",
    content:
      "in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio",
    created: "1649988444000",
  },
  {
    avatar: "https://robohash.org/quiquidemsint.png?size=50x50&set=set1",
    id: 9,
    first_name: "Lizzy",
    last_name: "Blinkhorn",
    email: "lblinkhorn8@reuters.com",
    gender: "Female",
    content:
      "et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut",
    created: "1660117900000",
  },
  {
    avatar: "https://robohash.org/rerumestoptio.png?size=50x50&set=set1",
    id: 10,
    first_name: "Uta",
    last_name: "Clench",
    email: "uclench9@tinyurl.com",
    gender: "Female",
    content:
      "congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec",
    created: "1660694303000",
  },
];

export const marketplaceUsers = [
  {
    avatar: "https://avatars.githubusercontent.com/u/115781894?s=60&v=4",
    id: 10,
    first_name: "Uta",
    last_name: "Clench",
    email: "uclench9@tinyurl.com",
    position: "Generalist/Matisse Specialist",
    gender: "Female",
    reviews: 3,
    content:
      "congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec",
    created: "1660694303000",
  },
  {
    avatar: "https://avatars.githubusercontent.com/u/115781894?s=60&v=4",
    id: 10,
    first_name: "Uta",
    last_name: "Clench",
    email: "uclench9@tinyurl.com",
    position: "Generalist/Matisse Specialist",
    gender: "Female",
    reviews: 2,
    content:
      "congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec",
    created: "1660694303000",
  },
  {
    avatar: "https://avatars.githubusercontent.com/u/115781894?s=60&v=4",
    id: 10,
    first_name: "Uta",
    last_name: "Clench",
    email: "uclench9@tinyurl.com",
    position: "Generalist/Matisse Specialist",
    gender: "Female",
    reviews: 5,
    content:
      "congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec",
    created: "1660694303000",
  },
  {
    avatar: "https://avatars.githubusercontent.com/u/115781894?s=60&v=4",
    id: 10,
    first_name: "Uta",
    last_name: "Clench",
    email: "uclench9@tinyurl.com",
    position: "Generalist/Matisse Specialist",
    gender: "Female",
    reviews: 5,
    content:
      "congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec",
    created: "1660694303000",
  },
  {
    avatar: "https://avatars.githubusercontent.com/u/115781894?s=60&v=4",
    id: 10,
    first_name: "Uta",
    last_name: "Clench",
    email: "uclench9@tinyurl.com",
    position: "Generalist/Matisse Specialist",
    gender: "Female",
    reviews: 4,
    content:
      "congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec",
    created: "1660694303000",
  },
  {
    avatar: "https://avatars.githubusercontent.com/u/115781894?s=60&v=4",
    id: 10,
    first_name: "Uta",
    last_name: "Clench",
    email: "uclench9@tinyurl.com",
    position: "Generalist/Matisse Specialist",
    gender: "Female",
    reviews: 5,
    content:
      "congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec",
    created: "1660694303000",
  },
  {
    avatar: "https://avatars.githubusercontent.com/u/115781894?s=60&v=4",
    id: 10,
    first_name: "Uta",
    last_name: "Clench",
    email: "uclench9@tinyurl.com",
    position: "Generalist/Matisse Specialist",
    gender: "Female",
    reviews: 1,
    content:
      "congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec",
    created: "1660694303000",
  },
  {
    avatar: "https://avatars.githubusercontent.com/u/115781894?s=60&v=4",
    id: 10,
    first_name: "Uta",
    last_name: "Clench",
    email: "uclench9@tinyurl.com",
    position: "Generalist/Matisse Specialist",
    gender: "Female",
    reviews: 5,
    content:
      "congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec",
    created: "1660694303000",
  },
  {
    avatar: "https://avatars.githubusercontent.com/u/115781894?s=60&v=4",
    id: 10,
    first_name: "Uta",
    last_name: "Clench",
    email: "uclench9@tinyurl.com",
    position: "Generalist/Matisse Specialist",
    gender: "Female",
    reviews: 5,
    content:
      "congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec",
    created: "1660694303000",
  },
  {
    avatar: "https://avatars.githubusercontent.com/u/115781894?s=60&v=4",
    id: 10,
    first_name: "Uta",
    last_name: "Clench",
    email: "uclench9@tinyurl.com",
    position: "Generalist/Matisse Specialist",
    gender: "Female",
    reviews: 5,
    content:
      "congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec",
    created: "1660694303000",
  },
  {
    avatar: "https://avatars.githubusercontent.com/u/115781894?s=60&v=4",
    id: 10,
    first_name: "Uta",
    last_name: "Clench",
    email: "uclench9@tinyurl.com",
    position: "Generalist/Matisse Specialist",
    gender: "Female",
    reviews: 5,
    content:
      "congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec",
    created: "1660694303000",
  },
  {
    avatar: "https://avatars.githubusercontent.com/u/115781894?s=60&v=4",
    id: 10,
    first_name: "Uta",
    last_name: "Clench",
    email: "uclench9@tinyurl.com",
    position: "Generalist/Matisse Specialist",
    gender: "Female",
    reviews: 5,
    content:
      "congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec",
    created: "1660694303000",
  },
  {
    avatar: "https://avatars.githubusercontent.com/u/115781894?s=60&v=4",
    id: 10,
    first_name: "Uta",
    last_name: "Clench",
    email: "uclench9@tinyurl.com",
    position: "Generalist/Matisse Specialist",
    gender: "Female",
    reviews: 5,
    content:
      "congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec",
    created: "1660694303000",
  },
  {
    avatar: "https://avatars.githubusercontent.com/u/115781894?s=60&v=4",
    id: 10,
    first_name: "Uta",
    last_name: "Clench",
    email: "uclench9@tinyurl.com",
    position: "Generalist/Matisse Specialist",
    gender: "Female",
    reviews: 5,
    content:
      "congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec",
    created: "1660694303000",
  },
];
